name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Java and Maven - setup settings.xml
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          server-id: github
          cache: 'maven'

      - name: Setup maven private repositories
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: >
              [
                {
                  "id": "bar",
                  "name": "Bonita Artifact Repository",
                  "url": "https://bonitasoft.jfrog.io/artifactory/releases",
                  "releases": {
                    "enabled": "true"
                  },
                  "snapshots": {
                    "enabled": "false"
                  }
                },
                {
                  "id": "github-presales",
                  "name": "github-presales",
                  "url": "https://maven.pkg.github.com/bonitasoft-presales/*",
                  "releases": {
                    "enabled": "true"
                  },
                  "snapshots": {
                    "enabled": "true"
                  }
                },
                {
                  "id": "github-laurent",
                  "name": "github-presales",
                  "url": "https://maven.pkg.github.com/laurentleseigneur/*",
                  "releases": {
                   "enabled": "true"
                  },
                  "snapshots": {
                   "enabled": "true"
                  }
                }
              ]
          plugin_repositories: >
              [
                {
                  "id": "bar",
                  "name": "Bonita Artifact Repository",
                  "url": "https://bonitasoft.jfrog.io/artifactory/releases",
                  "releases": {
                    "enabled": "true"
                  },
                  "snapshots": {
                    "enabled": "false"
                  }
                }
              ]
          servers: >
              [
                {
                  "id": "bar",
                  "username": "${{ secrets.JFROG_USER }}",
                  "password": "${{ secrets.JFROG_TOKEN }}"
                },
                {
                  "id": "github-presales",
                  "username": "${{ secrets.GHP_USER }}",
                  "password": "${{ secrets.GHP_TOKEN }}"
                },
                {
                  "id": "github-laurent",
                  "username": "${{ secrets.GHP_USER }}",
                  "password": "${{ secrets.GHP_TOKEN }}"
                }
              ]

      - name: Build and Test
        run: ./mvnw --batch-mode --no-transfer-progress clean verify

      - name: Publish to Github Package
        run: ./mvnw --batch-mode --no-transfer-progress deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

