name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Java and Maven - setup settings.xml
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          server-id: github
          cache: 'maven'

      - name: Build and Test
        run: ./mvnw --batch-mode --no-transfer-progress clean verify

      - name: Publish to Github Package
        run: ./mvnw --batch-mode --no-transfer-progress deploy
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
